### ISSUE TITLE
Solution works with Ubuntu Unity 16.04

### ISSUE THREAD

**Issue by hopugop** [marianosimone/epub-thumbnailer#10]
I ran the install script and got an error that Distribution could not be detected so epub-thumbnailer could be used to manually generate thumbnails.

Looking at the script I noticed that for Gnome 3 or xfce4 the script would just copy epub.thumbnailer from the src directory to /usr/share/thumbnailers/, so I did just that and hit refresh on Nautilus. Thumbnails are generated normally.

Maybe you could just add a check for Unity (or maybe just Nautilus in general?) and install it there.

**Comment by marianosimone** [comment]
Thanks @hopugop!

I've been adding installation support as soon as I got my hands on different environments where I could test it. Could you help me out by telling me what the following commands return?

- `ps -A | grep unity`
- `ps -A | grep nautilus`
- `unity --version`

**Comment by hopugop** [comment]
I threw in a nautilus version as well.
```
~$ ps -A | grep unity
 1745 ?        00:00:02 unity-settings-
 1758 ?        00:00:26 unity-panel-ser
 1989 ?        00:00:00 unity-fallback-
 5727 ?        00:00:00 unity-scope-hom
 5738 ?        00:00:00 unity-scope-loa
 5740 ?        00:00:00 unity-files-dae
~$ ps -A | grep nautilus
 2020 ?        00:02:05 nautilus
~$ unity --version
unity 7.4.0
~$ nautilus --version
GNOME nautilus 3.14.3
~$ ps auxww | grep unity
user  1745  0.0  0.2 1055524 28244 ?       Ssl  15:35   0:02 /usr/lib/unity-settings-daemon/unity-settings-daemon
user  1758  0.1  0.2 639688 32908 ?        Ssl  15:35   0:26 /usr/lib/x86_64-linux-gnu/unity/unity-panel-service
user  1989  0.0  0.1 569964 17656 ?        Sl   15:35   0:00 /usr/lib/unity-settings-daemon/unity-fallback-mount-helper
user  5727  0.0  0.1 645116 13344 ?        Sl   18:54   0:00 /usr/lib/x86_64-linux-gnu/unity-scope-home/unity-scope-home
user  5738  0.0  0.2 589984 24988 ?        Sl   18:54   0:00 /usr/bin/unity-scope-loader applications/applications.scope applications/scopes.scope commands.scope
user  5740  0.0  0.0 680080 10976 ?        Sl   18:54   0:00 /usr/lib/x86_64-linux-gnu/unity-lens-files/unity-files-daemon
~$ 
```

**Comment by marianosimone** [comment]
Thanks a lot!

I've actually been able to get a machine with Unity in it, and I've updated the installer to support it.

If you can/want, try removing your manual installation and reinstall using the installer to see if it works ;)

Thanks again for taking the time to report!

**Comment by hopugop** [comment]
I also tested on a brand new installation, it's working great! Thank you for the time to work on this, the project is great!
