### ISSUE TITLE
Thumnbailer not working in Ubuntu Gnome 16.04

### ISSUE THREAD

**Issue by dondurito** [marianosimone/epub-thumbnailer#11]
Hi there,

although I followed your instrucitions precisely the epub thumbnailer is not working on my machine. Nautilus still shows the general icons.

I'm running Ubuntu Gnome 16.04.

Hope you can help me with this matter,
thanks, Don

**Comment by marianosimone** [comment]
Hi @dondurito. A couple of questions to diagnose your problem:

1. Did the installation run successfully?
2. Did you try running the command manually for a given epub (e.g. `epub-thumbnailer ~/some_book.epub ~/cover.png 100`)?
3. What's the output of:
-  `gnome-session --version`
- `ps -A | egrep -i mate|gnome|xfce4|unity`
4. What file manager are you using? (Nautilus? Thunar?)

Thanks!

**Comment by dondurito** [comment]
hey @marianosimone - thanks for your quick reply.

1. Installation ran successfully without any error messages
2. command doesn't give any error message but still no cover is shown

4. command doesn't give any output. usr/share/gnome/gnome-version.xml states that I'm using 3.18.2
5. tells me that the commands gnome an xfce4 can't be found and that unity at the moment is not installed but I could install it (what I don't want)
6. I'm using Nautilus

I hope these information can give any hint. Thanks!

**Comment by marianosimone** [comment]
Given that the extraction is not working, let's try something else:

1.Would you mind trying with this book? https://dl.dropboxusercontent.com/u/241376/Roberto%20Arlt%20-%20Los%20Siete%20Locos.epub
2. If possible, could you provide me the book you tried and didn't work?
3. What's the output of `python --version`?

**Comment by dondurito** [comment]
1. As I edited my post yesterday - extraction to png-file works (I missunderstood the usage of manual extraction at first) with you ebook as well as with mine. Still nautilus shows no cover.
2. Tried it with that book: [](https://www.dropbox.com/s/4nw13hcjcom9ijb/Macht%20und%20Widerstand%20-%20Ilija%20Trojanow.epub?dl=0) ...same here, extraction works, cover stil not shown
3. `Python 2.7.12`

**Comment by passerbyGitHub** [comment]
I'm using Ubuntu-Gnome 16.10
1. Installation run successfully
2. Cover is extracted and saved to png.file
3. GNOME Shell 3.22.0
4. Nautilus
5. Python 2.7.12+

I've the same problem as dondurito until I restart "nautilus -q"  and delete all files in ~/.cache/thumbnails.

Thank you marianosimone for this nice program!

**Comment by marianosimone** [comment]
Thanks for the comment, @passerbyGitHub!

@dondurito can you confirm if any of that helps?

**Comment by dondurito** [comment]
thanks for the suggestion @passerbyGitHub - did that but no change. Still no covers shown and no thumbnails created in ~/.cache/thumbnails

I think I will try to set up Ubuntu 16.04 and Ubuntu Gnome in a VirtualMachine and try the script on a fresh install. Maybe I screwed something up when setting my system.

**Comment by marianosimone** [comment]
@dondurito Thanks for the follow up!

I'll take a look at why the installation didn't fail even if you didn't have `python-imaging`. Good catch!

Now, there's one more thing it would be nice to try, and maybe that would fix the issue for you. Can you try modifying `src/epub.thumbnailer`, changing `Exec=/usr/bin/epub-thumbnailer %i %o %s` for `Exec=/usr/bin/epub-thumbnailer %u %o %s` before installing (or directly in the thumbnailer, where it was installed?

I see a `,` in the input file name, and that *might* be causing issues

(BTW: next time, instead of editing your comment, add a new one, so watchers of the topic - including me - get notifications!)

**Comment by dondurito** [comment]
Hey @marianosimone,

I reinstalled Ubuntu yesterday and your script is working like a charm. Don't know what I messed up at the last installation. Maybe it was the migration of the thumbnails folder from my old system to the new one. I skipped that this time.

Thanks for your help and for your great thumbnailer ... finally it's fun again to browse my ebooks!

**Comment by marianosimone** [comment]
@dondurito you are welcome, glad to see it's working now 👍
