### ISSUE TITLE
Not working on linux Mint 17.3 with XFCE

### ISSUE THREAD

**Issue by pebmp17** [marianosimone/epub-thumbnailer#12]
Hi, I installed the thumbnailer but even after logging out, none of my epubs would show the thumbnail. I am using Linux Mint 17.3, which is based in Ubuntu 14.04, and with the XFCE 4.12 desktop environment. Also, I saw the issue below, but preferred to make my own, just in case the problems are different. So, I will already answer some of your questions
1. Yes, the installation went  successfully
2. Yes, the command does extracts the cover
3. (Not so sure if it will help since I am using XFCE, but..) `gnome-session --version = gnome-session 3.9.90`
4. That command didn't work, just threw a bunch of command not found (Seems like you forgot the quotes, correcting it gives this output):
   17 ?        00:00:00 kdevtmpfs
   1586 ?        00:00:00 xfce4-session
   1598 ?        00:00:18 xfce4-panel
   1611 ?        00:00:00 polkit-gnome-au
   1637 ?        00:00:02 xfce4-power-man
   1645 ?        00:00:00 xfce4-volumed
   7049 ?        00:00:01 xfce4-notifyd
   8445 ?        00:00:00 gnome-terminal
   8449 ?        00:00:00 gnome-pty-helpe
5. I am using both nemo and Thunar and both of them the thumbnail doesn't appear.

By the way, I think that I might have lost pdf thumbnails,  not so sure if your program can cause that, but thought it might be good to mention.

**Comment by marianosimone** [comment]
Hi @pebmp17, thanks for the report!

I've been having a hard time getting the thumbnailer to work with XFCE/thunar for a while and I don't have access to a box with that config right now (I'll try to get one ASAP and reproduce).

Meanwhile, a long shot (as listed [here](http://www.geocities.jp/cabezon_hashimoto/doc/thunar/C/customizing-thunar.html)) is to regenerate the thumbnailers cache: `/usr/libexec/thunar-vfs-update-thumbnailers-cache-1` to see if that helps.

Sorry about the PDF thumbnails... `epub-thumbnailer` shouldn't mess that up, but I'd try uninstalling it to see if that fixes it (if it does, we might be into something)

**Comment by pebmp17** [comment]
The command didn't work, just gave a`File or directory not found`, uninstalling doesn't helped and even installing again the epub thumbnailer didn't change a thing on any thumbnails.

**Comment by marianosimone** [comment]
Thanks for the follow up. I finally got XFCE installed on my box and couldn't get it to work either. I'm looking into it, but I'd appreciate any other insights you might have about this (if any)

Will keep this updated with my findings :)

**Comment by pebmp17** [comment]
Actually, yes I do. Really not so sure how it happened, but when I saw your comment I reinstalled the program to try do find something new to help you. Unexpectedly, this time the pdf thumbnails are working again and the epub ones are actually working in Nemo this time (Epub thumbnails still aren't generated in Thunar, but I can see now them since they were successfully generated by Nemo). Kinda odd they both started working together, it perhaps may have some connection between the malfunctioning of both after all.

Github shows me that you actually haven't changed anything since my last try, so I really don't have any clue what happened here. Anyway, huge thank you for still keep looking into this issue and hope you can make some progress in Thunar.

**Comment by marianosimone** [comment]
Thanks a lot for the insights! It seems like the problem is not in XFCE then, but in Thunar. I went ahead and created a ticket for that and will try to come up with a solution there.

**Comment by pebmp17** [comment]
Yep, seems to be the right thing to do. Also, I am now using Arch Linux with XFCE and everything is the same here, so XFCE really isn't  the culprit. Again, thanks for everything and good luck with the project.
