### ISSUE TITLE
Thumbnails not being generated by Thunar

### ISSUE THREAD

**Issue by marianosimone** [marianosimone/epub-thumbnailer#13]
It might have to do with the installation process

Reported originally as #12

**Comment by JHTrans** [comment]
After following the other instructions provided, one additional step was required for me to have ebook thumbnails in Thunar. I appended the following to /etc/xdg/tumbler/tumbler.rc:

```
# Ebook thumbnailer
[EbookThumbnailer]
Disabled=false
Priority=1
Locations=
MaxFileSize=0

```
Thumbnails appeared after clearing the cache and restarting (logging out and in may be enough, however).

**Comment by marianosimone** [comment]
Thanks a lot for the instructions, @JHTrans , they seem to work perfectly!
