### ISSUE TITLE
Thumbnailer on Mint 17.1 and 18 Cinnamon

### ISSUE THREAD

**Issue by j-str** [marianosimone/epub-thumbnailer#14]
Hi,
sorry to bother you with this. I'm happily using epub-thumbnailer with Linux Mint 17.1/Cinnamon installed on an older notebook some time ago. Unfortunately, I am not able to make it work on a different computer, running Linux Mint 18 / Cinnamon 3.0.7.

On Mint 17.1 / Cinnamon 2.4.8, using the command you asked for in an older post,  I get:
js@js-X201 ~ $ ps -A | egrep -i "mate|gnome|xfce4|unity"
 1711 ?        00:00:00 gnome-keyring-d
 2256 ?        00:00:00 polkit-gnome-au
 4256 ?        00:00:00 gnome-terminal
 4262 ?        00:00:00 gnome-pty-helpe

js@js-X201 ~ $ gnome-shell --version
GNOME Shell 3.10.4

When installing on  Mint 18 I first got  "sh: 1: gnome-shell: not found". After installing Gnome shell etc., installation was finished sucessfully and I can manually extract "cover.png" via "epub-thumbnailer  title.epub cover.png 128". However, no thumbnails are shown for the epub-files. I cleared .cache and restarted Nemo.

On Mint 18 / Cinnamon 3.0.7 I get:
js@js-MSI1 ~ $ ps -A | egrep -i "mate|gnome|xfce4|unity"
 2021 ?        00:00:00 gnome-keyring-d
 2351 ?        00:00:00 polkit-gnome-au
 7013 ?        00:00:06 gnome-terminal-

js@js-MSI1 ~ $ gnome-shell --version
GNOME Shell 3.18.5

You have an idea what could be the issue here? 
(Sorry, I lack knowledge of Linux and neither do I understand your script...I'm just a user....)
Thanks!

**Comment by marianosimone** [comment]
Hi @j-str, thanks a lot for reporting this. It seems like the installation process is a bit fragile and it's not working in as many environments as I'd like.

Did you try any other file manager to see if everything looks ok there? (Nautilus seems to always work, and I've seen mixed experiences with Thunar... I think you are the first one reporting on Nemo). In case it works in Nautilus for you, then I can try to reproduce the problem using Nemo, but first I want to see if everything looks installed correctly.

Thanks!

**Comment by j-str** [comment]
Unfortunately not working for me with Nautilus either. I installed it, cleaned .cache again. But still no thumbs - in Nautilus. 

(I would suspect that it is a change in Mint 18 compared to Mint 17. For example, If I remember correctly I did not have to install gnome shell etc. when I installed epub-thumbnailer on 17.1. Though python was missing I think. Are there some packages that epub-thumbnailer depends on, that I could check?)

Btw. - which files would I have to delete to 'uninstall' epub-thumbnailer for a 'fresh' installation?
Thanks!

**Comment by marianosimone** [comment]
Installation of gnome-shell might be needed now if Mint changed their default packages. As I said, my installation process is pretty brittle and seems to have a lot of issues with new releases. I'm trying to get someone with more knowledge on that to help me out :)

As per a clean installation, you should be able to run the uninstaller with:

`sudo python install.py uninstall`

Then, to check if that worked, you can see if the following files were removed:

- `/usr/bin/epub-thumbnailer`
- `/usr/share/thumbnailers/epub.thumbnailer`

**Comment by j-str** [comment]
I tried uninstall & fresh install of epub-thumbnailer - without success.

Thanks a lot for your fast replies!  
Looking forward to further suggestions when you find somebody who can have a look into Mint 18.

**Comment by flurpfoobar** [comment]
Thunar 1.16.11 in Linux Mint 18.3 Sylvia (XFCE) (64Bit) and your thumbnailer does not work.
However with PCManFM it works. Thumbnails created by PCManFM is reused by Thunar, but it is not a workaround I like.

**Comment by marianosimone** [comment]
Thanks for reporting @flurpfoobar.

Can you check if the instructions listed [here](https://github.com/marianosimone/epub-thumbnailer/issues/13#issuecomment-427756919) work for you?

If so, I'll see how I can add that to the installation process itself.

**Comment by marianosimone** [comment]
Closing as inactive
