### ISSUE TITLE
Support for GVFS

### ISSUE THREAD

**Issue by Laserlicht** [marianosimone/epub-thumbnailer#15]
At the moment it's not compatible with gvfs e.g. smb://. (Previews everywhere enabled in the Caja-Settings)

I've added to my .py:
`import gio`

`if input_file.find('://') >= -1:`
`     f = gio.File(input_file)`
`     input_file = f.get_path()`

and changed my .thumbnailer:
`Exec=/usr/bin/epub-thumbnailer %i %o %s`
to
`Exec=/usr/bin/epub-thumbnailer %u %o %s`

But I think there are better solutions...

**Comment by marianosimone** [comment]
Hi @Laserlicht, thanks a lot for the report and the implementation idea!

I've just made a change to the code (based on your suggestion), and I think that should add support for mounted devices.

Could you please try it out and verify?

Thanks again!
