### ISSUE TITLE
Works in pcmanfm

### ISSUE THREAD

**Issue by subgitlab** [marianosimone/epub-thumbnailer#16]
Installing epub-thumbnailer to /usr/bin/ ...
OK
sh: 1: gnome-session: not found
sh: 1: gnome-shell: not found
Could not determine your desktop environment version. You can still use the thumbnailer script manually.

Bunsenlab debian stretch 
I found that it install.py install /usr/bin/epub-thumbnailer but omits /usr/share/thumbnailers/epub.thumbnailer

I manually copy from master/src to /usr/share/thumbnailers/epub.thumbnailer and it worked with majority of epubs.

## Thanks very much

![epub cover](https://user-images.githubusercontent.com/38258950/39569960-13685d68-4ec7-11e8-8d2f-4d11e3cab78b.png)

Saydyn

**Comment by marianosimone** [comment]
Hi @subgitlab, thanks for reporting!

I don't have an environment like yours to test this on, but I'd appreciate a Pull Request to add detection of your desktop environment. Not that the installer DOES install to `/usr/share/thumbnailers/epub.thumbnailer` if it thinks it's running in 'gnome3', 'xfce4' or 'unity'. Is there anything we can add to detect yours?

Thanks again!

**Comment by subgitlab** [comment]
It's solved as posted. above. I my case installer installed /usr/bin/epub-thumbnailer and ommited /usr/share/thumbnailers/epub.thumbnailer due to sh: 1: gnome-session: not found
sh: 1: gnome-shell: not found. Manual install copy, paste to /usr/share/thumbnailers/epub.thumbnailer solved. 
### I m grateful and just want add possible solution to other wm.

**Comment by marianosimone** [comment]
Thanks for the follow up, @subgitlab.

I just uploaded a fix that _should_ detect your environment correctly. Would you mind trying it out and letting me know how it goes?

**Comment by subgitlab** [comment]
I install again in debian strecth openbox and it worked.

## Thanks Marianosimone

**Comment by marianosimone** [comment]
Thanks for the follow up. Closing this issue!
