### ISSUE TITLE
Moksha window manager

### ISSUE THREAD

**Issue by coderavventura** [marianosimone/epub-thumbnailer#17]
Hello,
I was not able to install epub-thumbnailer on my Moksha desktop.
Moksha is a fork of enlightenment, and is originally found in Bodhi Linux.
However, I have it installed on ubuntu. I use the Caja file manager.
Here is the long list of "ps -A"

  PID TTY          TIME CMD
    1 ?        00:00:11 systemd
    2 ?        00:00:00 kthreadd
    4 ?        00:00:00 kworker/0:0H
    6 ?        00:00:00 mm_percpu_wq
    7 ?        00:00:00 ksoftirqd/0
    8 ?        00:07:50 rcu_preempt
    9 ?        00:00:00 rcu_sched
   10 ?        00:00:00 rcu_bh
   11 ?        00:03:05 rcuop/0
   12 ?        00:00:00 rcuos/0
   13 ?        00:00:00 rcuob/0
   14 ?        00:00:00 rcuc/0
   15 ?        00:00:00 rcub/0
   16 ?        00:00:00 migration/0
   17 ?        00:00:03 watchdog/0
   18 ?        00:00:00 cpuhp/0
   19 ?        00:00:00 cpuhp/1
   20 ?        00:00:05 watchdog/1
   21 ?        00:00:00 migration/1
   22 ?        00:00:00 rcuc/1
   23 ?        00:00:00 ksoftirqd/1
   25 ?        00:00:00 kworker/1:0H
   26 ?        00:00:08 rcuop/1
   27 ?        00:00:00 rcuos/1
   28 ?        00:00:00 rcuob/1
   29 ?        00:00:00 cpuhp/2
   30 ?        00:00:01 watchdog/2
   31 ?        00:00:00 migration/2
   32 ?        00:00:00 rcuc/2
   33 ?        00:00:00 ksoftirqd/2
   35 ?        00:00:00 kworker/2:0H
   36 ?        00:03:22 rcuop/2
   37 ?        00:00:00 rcuos/2
   38 ?        00:00:00 rcuob/2
   39 ?        00:00:00 cpuhp/3
   40 ?        00:00:07 watchdog/3
   41 ?        00:00:00 migration/3
   42 ?        00:00:00 rcuc/3
   43 ?        00:00:00 ksoftirqd/3
   45 ?        00:00:00 kworker/3:0H
   46 ?        00:00:07 rcuop/3
   47 ?        00:00:00 rcuos/3
   48 ?        00:00:00 rcuob/3
   49 ?        00:00:00 kdevtmpfs
   50 ?        00:00:00 netns
   54 ?        00:00:00 khungtaskd
   55 ?        00:00:00 oom_reaper
   56 ?        00:00:00 writeback
   57 ?        00:00:00 kcompactd0
   58 ?        00:00:00 ksmd
   59 ?        00:00:03 khugepaged
   60 ?        00:00:00 crypto
   61 ?        00:00:00 kintegrityd
   62 ?        00:00:00 bioset
   63 ?        00:00:00 kblockd
   65 ?        00:00:00 ata_sff
   66 ?        00:00:00 md
   67 ?        00:00:00 edac-poller
   68 ?        00:00:00 devfreq_wq
   69 ?        00:00:00 watchdogd
   72 ?        00:00:00 kauditd
   73 ?        00:00:00 kswapd0
   74 ?        00:00:00 bioset
   75 ?        00:00:00 ecryptfs-kthrea
  118 ?        00:00:00 kthrotld
  119 ?        00:00:00 acpi_thermal_pm
  120 ?        00:00:00 bioset
  121 ?        00:00:00 bioset
  122 ?        00:00:00 bioset
  123 ?        00:00:00 bioset
  124 ?        00:00:00 bioset
  125 ?        00:00:00 bioset
  126 ?        00:00:00 bioset
  127 ?        00:00:00 bioset
  135 ?        00:00:00 ipv6_addrconf
  158 ?        00:00:00 charger_manager
  207 ?        00:00:00 scsi_eh_0
  208 ?        00:00:00 scsi_tmf_0
  209 ?        00:00:00 scsi_eh_1
  210 ?        00:00:00 scsi_tmf_1
  211 ?        00:00:00 scsi_eh_2
  212 ?        00:00:00 scsi_tmf_2
  213 ?        00:00:00 scsi_eh_3
  214 ?        00:00:00 scsi_tmf_3
  215 ?        00:00:00 scsi_eh_4
  216 ?        00:00:00 scsi_tmf_4
  217 ?        00:00:00 scsi_eh_5
  218 ?        00:00:00 scsi_tmf_5
  224 ?        00:00:00 bioset
  225 ?        00:00:00 bioset
  227 ?        00:00:00 kworker/1:1H
  228 ?        00:00:00 kworker/0:1H
  230 ?        00:00:01 kworker/2:1H
  234 ?        00:00:00 i915/signal:0
  235 ?        00:00:00 i915/signal:1
  236 ?        00:00:00 i915/signal:2
  304 ?        00:00:00 kworker/3:1H
  328 ?        00:00:11 jbd2/sda1-8
  329 ?        00:00:00 ext4-rsv-conver
  375 ?        00:00:07 systemd-journal
  413 ?        00:00:00 systemd-udevd
  588 ?        00:00:00 irq/27-mei_me
  598 ?        00:00:00 kmemstick
  878 ?        00:00:00 kworker/u17:0
  879 ?        00:00:00 hci0
  880 ?        00:00:00 hci0
  881 ?        00:00:00 kworker/u17:1
  888 ?        00:00:21 jbd2/sda2-8
  889 ?        00:00:00 ext4-rsv-conver
 1204 ?        00:00:00 cfg80211
 1219 ?        00:00:00 rpcbind
 1223 ?        00:00:07 avahi-daemon
 1224 ?        00:00:00 avahi-dnsconfd
 1225 ?        00:00:04 rsyslogd
 1228 ?        00:00:00 smartd
 1230 ?        00:00:00 cron
 1232 ?        00:00:23 dbus-daemon
 1239 ?        00:00:00 systemd-logind
 1240 ?        00:00:01 ofonod
 1242 ?        00:00:00 cupsd
 1243 ?        00:00:00 bluetoothd
 1244 ?        00:00:15 acpid
 1245 ?        00:00:22 thermald
 1247 ?        00:00:21 NetworkManager
 1248 ?        00:00:04 accounts-daemon
 1255 ?        00:00:09 snapd
 1323 ?        00:00:01 atop
 1356 ?        00:00:00 avahi-daemon
 1362 ?        00:00:00 krfcommd
 1367 ?        00:00:04 cups-browsed
 1387 ?        00:00:03 irqbalance
 1428 ?        00:00:00 lightdm
 1471 ?        00:00:07 polkitd
 1481 ?        00:00:00 colord
 1487 ?        00:00:33 vnstatd
 1489 ?        00:00:00 sshd
 1496 ?        00:00:00 sh
 1501 ?        00:05:21 boinc
 1517 tty7     00:12:15 Xorg
 1530 ?        00:00:05 wpa_supplicant
 1780 ?        00:00:00 lightdm
 1784 ?        00:00:00 whoopsie
 1821 tty1     00:00:00 agetty
 1836 ?        00:00:10 ntpd
 1847 ?        00:00:45 tor
 1857 ?        00:00:02 apache2
 1860 ?        00:00:33 apache2
 1861 ?        00:00:31 apache2
 1966 ?        00:01:11 collectl
 2487 ?        00:00:00 systemd
 2488 ?        00:00:00 (sd-pam)
 2495 ?        00:00:05 enlightenment_s
 2570 ?        00:00:00 ssh-agent
 2573 ?        00:00:00 dbus-launch
 2574 ?        00:00:01 dbus-daemon
 2584 ?        00:00:26 ibus-daemon
 2585 ?        00:02:05 enlightenment
 2589 ?        00:00:00 gvfsd
 2594 ?        00:00:00 gvfsd-fuse
 2603 ?        00:00:00 ibus-dconf
 2604 ?        00:00:06 ibus-ui-gtk3
 2606 ?        00:00:03 ibus-x11
 2608 ?        00:00:00 at-spi-bus-laun
 2613 ?        00:00:01 dbus-daemon
 2615 ?        00:00:25 at-spi2-registr
 2627 ?        00:00:02 efreetd
 2663 ?        00:00:08 ibus-engine-sim
 2666 ?        00:00:04 enlightenment_f
 2675 ?        00:00:05 udisks-daemon
 2676 ?        00:00:00 udisks-daemon
 6174 ?        00:01:03 qterminal
 6181 pts/0    00:00:00 zsh
 6251 ?        00:00:42 caja
 6257 ?        00:00:00 gvfs-udisks2-vo
 6260 ?        00:00:03 udisksd
 6268 ?        00:00:00 gvfs-mtp-volume
 6273 ?        00:00:00 gvfs-afc-volume
 6279 ?        00:00:00 gvfs-goa-volume
 6283 ?        00:00:00 goa-daemon
 6291 ?        00:00:00 goa-identity-se
 6293 ?        00:00:07 mission-control
 6296 ?        00:00:00 gvfs-gphoto2-vo
 6308 ?        00:00:00 gvfsd-trash
 6324 ?        00:00:00 gvfsd-metadata
 6326 ?        00:00:00 dconf-service
 6346 ?        00:14:40 chromium-browse
 6380 ?        00:00:00 chromium-browse
 6382 ?        00:00:00 chromium-browse
 6411 ?        00:07:28 chromium-browse
 6432 ?        00:00:00 chromium-browse
 6638 ?        00:00:07 pulseaudio
 6752 ?        00:00:03 chromium-browse
 6765 ?        00:00:06 chromium-browse
 6867 ?        00:01:34 chromium-browse
 7689 ?        00:01:10 chromium-browse
11050 ?        00:00:00 gconfd-2
11062 ?        00:00:00 kdeinit4
11065 ?        00:00:00 klauncher
11067 ?        00:00:02 kded4
11615 ?        00:00:17 kworker/2:2
12641 ?        00:00:13 chromium-browse
12760 ?        00:00:11 chromium-browse
13016 ?        00:00:00 kworker/1:0
13441 ?        00:00:00 mate-settings-d
13813 ?        00:00:00 gvfsd-network
13831 ?        00:00:01 gvfsd-dnssd
14751 ?        00:00:28 kworker/u16:3
23200 ?        00:00:04 kworker/0:1
23616 ?        00:00:12 kworker/u16:1
24102 ?        00:00:01 kworker/3:1
24235 ?        00:00:07 kworker/u16:0
24282 ?        00:00:00 dhclient
24356 ?        00:00:08 kworker/u16:2
24482 ?        00:00:01 kworker/3:0
24530 ?        00:00:00 kworker/2:1
24540 ?        00:00:00 kworker/0:0
24855 ?        00:00:00 kworker/1:2
24946 ?        00:00:08 audacious
25100 ?        00:00:00 kworker/2:0
25117 ?        00:00:00 efl_net_proxy_h
25129 pts/0    00:00:00 ps

**Comment by marianosimone** [comment]
Thanks for the information, @coderavventura!

Did you try installing manually (by copying the files) instead of using the installer? If that work, I can probably improve the installer to detect your environment as a known one.

If not, I'd need to figure out the locations/file formats needed

**Comment by coderavventura** [comment]
The manual installation worked fine.
I have changed the line _environment = check_desktop_env()_ in _install.py_ to
environment = 'gnome2' [didn't worked] and environment = 'xfce4' [worked perfectly]
Maybe this could be added in comments.

About detecting Moksha, the command 'wmctrl -m' shows the following output in terminal:
Name: Moksha
Class: N/A
PID: 2106
Window manager's "showing the desktop" mode: N/A

**Comment by marianosimone** [comment]
Thanks a lot for the information!

Would you mind testing the installer again? I just merged a change that should fix it!

**Comment by coderavventura** [comment]
It worked! Thanks!
