### ISSUE TITLE
Gnome-shell Window manager warnings in Ubuntu Cosmic

### ISSUE THREAD

**Issue by arky** [marianosimone/epub-thumbnailer#23]
epub-thumbnailer (1.0) fails to work on latest Ubuntu. The following logs are seen in syslog:

`Feb 13 14:54:56 Think org.gnome.Shell.desktop[3587]: Window manager warning: 0x1c00016 (epub-thumb) appears to be one of the offending windows with a timestamp of 9172827.  Working around...
Feb 13 14:54:57 Think org.gnome.Shell.desktop[3587]: Window manager warning: 0x1c00016 (epub-thumb) appears to be one of the offending windows with a timestamp of 9172861.  Working around...
`

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.10
Release:	18.10
Codename:	cosmic

$ python --version
Python 2.7.15+

$ nautilus --version
GNOME nautilus 3.26.4

**Comment by marianosimone** [comment]
HI @arky, thanks for the report!

Do you have any more information you can share about what's going on? Is the system misbehaving in any way? are thumbnails being created? are there any special conditions that may make this happen (e.g. a directory with many files? a mounted external/over the network filesystem?)

**Comment by arky** [comment]
@marianosimone 

Running the script manually works without any problem but epub thumbnails are being created in nautilus. Is there anyway to debug nautilus plugins? 

Thanks!

**Comment by marianosimone** [comment]
I don't currently have access to a linux machine, so it's a bit hard for me to help you debug this. I think my previous questions still stand (not sure if you missed a *not* in your last comment): are the thumbnails being created? are there any special conditions that may make this happen (e.g. a directory with many files? a mounted external/over the network filesystem?)

Researching the particular warning, I see that almost always that message comes after another one saying something like: `Window manager warning: 0xAAAAAA (#something @ O) appears to be one of the offending windows with a timestamp of XXXXXX.  Working around...` is that the case for you?

**Comment by arky** [comment]
@marianosimone Sorry I missed that. It is shared Ubuntu ext4 partition mounted as local filesystem. There aren't many epub files on it.

**Comment by marianosimone** [comment]
Great, thanks for the update.

Seems like the problem is no longer that there are warnings, but that thumbnails are not generated 🤔

It would be interesting to see what `check_desktop_env` returns: https://github.com/marianosimone/epub-thumbnailer/blob/9fb3a1d6d9c999732258cc910568c17898ff54a6/install.py#L78 that way, we can probably see if the installation process is doing the right thing inferring the system

**Comment by marianosimone** [comment]
Closing as inactive
