### ISSUE TITLE
On Ubuntu 20.04 thumbnails are not generated

### ISSUE THREAD

**Issue by jhossettstalinn** [marianosimone/epub-thumbnailer#28]
I have installed it on the latest Ubuntu (20.04) with python3 correctly but on nautilus, thumbnails are not shown.

**Comment by marianosimone** [comment]
Hi @jhossettstalinn, thanks for reporting!

Can you provide some more info of what you see happening? Have you tried generating any thumbnails in the stand-alone script way?

**Comment by jhossettstalinn** [comment]
I've tried in the stand-alone script way for a file and it was find its cover without automatically generating its thumbnail (manually is a tiring task); I've done this after installing the package python-is-python3. Then just in case I've tried reinstalling the program and I still don't see the thumbnails. On Ubuntu 18 everything was ok. Thanks, regards.

**Comment by marianosimone** [comment]
Thanks for the extra context.

Unfortunately, I don't have access to an Ubuntu machine to test this out, so we'll have to wait until someone else has the time to dig into it.

The installation process itself is kind of brittle, and previous Ubuntu upgrades have broken it, and it has to do mainly with changes both to the file manager and the desktop environment 😞

**Comment by rauldipeas** [comment]
When i try to run manually, i'm getting this error...
```
Traceback (most recent call last):
  File "src/epub-thumbnailer.py", line 103, in <module>
    input_file = sys.argv[1]
IndexError: list index out of range
```

**Comment by marianosimone** [comment]
Hi @rauldipeas. Can you share the full command you are using to run manually? It looks like you are not sending enough parameters to it.

**Comment by rauldipeas** [comment]
Sorry, my mistake, it's run well right now.
