### ISSUE TITLE
Instructions for Pillow in readme

### ISSUE THREAD

**Issue by Jorge-Gonzalez** [marianosimone/epub-thumbnailer#29]
Installing Pillow in my case needed sudo, in Manjaro xfce.

**Comment by marianosimone** [comment]
Hi @Jorge-Gonzalez , thanks for reporting!

Did you install it with `pip` or with your package manager? Installation instructions really depend on the system where you are using it (and how you usually manage your configurations), so I tried not to get TOO prescriptive.

**Comment by Jorge-Gonzalez** [comment]
Hi, I cloned the epub-thumbnailer repo and used the install script.
________________________________
De: Mariano Simone <notifications@github.com>
Enviado: martes, 21 de julio de 2020 09:38
Para: marianosimone/epub-thumbnailer <epub-thumbnailer@noreply.github.com>
Cc: Jorge <jorge.gonzalez@live.com>; Assign <assign@noreply.github.com>
Asunto: Re: [marianosimone/epub-thumbnailer] Instructions for Pillow in readme (#29)


Assigned #29<https://github.com/marianosimone/epub-thumbnailer/issues/29> to @Jorge-Gonzalez<https://github.com/Jorge-Gonzalez>.

**Comment by marianosimone** [comment]
Sorry, I was asking about how you installed `pillow`, not `epub-thumbnailer`. The readme already states that `pillow` is a pre-requisite, and just gives guidance on how to install. I can add a note saying that you might need to use `sudo` (depending on your system and current config)

How does that sound?
