### ISSUE TITLE
Can't install on macOS

### ISSUE THREAD

**Issue by stardiviner** [marianosimone/epub-thumbnailer#33]
I try to install this script on macOS.

But it report error:

```
$ sudo python install.py install
Password:
Checking dependencies ...

Required dependencies:
    Python Imaging Library .......
OK

You do not have write permissions to /usr/bin/ (maybe you need to sudo)
```

I used `sudo` but install.py script still error I don't have sudo permission.

Do I need to do extra settings under macOS?

**Comment by marianosimone** [comment]
Hi @stardiviner!

The installation process is intended for linux usage (as that's where the concept of a thumbnailer makes sense), not for Mac.

You can still use the script as a stand alone one if you want to generate thumbnails for yourself. For that, you can read 
https://github.com/marianosimone/epub-thumbnailer#stand-alone

In that case, the only required dependency is Pillow, for which you can find the instructions in their [official docs](https://pillow.readthedocs.io/en/stable/installation.html#macos-installation)

**Comment by stardiviner** [comment]
I see, Thanks @marianosimone
