### ISSUE TITLE
Error running the script: python not found, even though it is installed

### ISSUE THREAD

**Issue by Yaglb** [marianosimone/epub-thumbnailer#36]
Hi,

I am not an expert Gnu/Linux user, so I may have done something wrong or missed something obvious but since I got the same error on my two machines and got it to work using the same solution I thought I might not be alone in having this issue.

Following the installation instructions, I got an error message when trying to run the install script using the `sudo python install.py install` command (on two Debian 11/Xfce PC). The shell was telling there was no python installed: `bash: python: command not found`. I tried to (re)install it using apt, but it told me it was already installed. 

Replacing 'python' by 'python3' (`sudo python3 install.py install`), the installation ran as as expected and everything is working great. Thank you so much for writing this, It's great to be able to display ebooks cover in the file manager :)

**Comment by marianosimone** [comment]
Thanks  for calling this out! I had already transitioned everything to `python3`, but the installation instructions still said just `python`. I'll add a comment about this being system-dependent :)
