### ISSUE TITLE
Pillow might need to be installed globally

### ISSUE THREAD

**Issue by greendost** [marianosimone/epub-thumbnailer#40]
Just a minor note - I think the thumbnailer requires a global installation of Pillow, instead of at the user level.

```sudo python3 install.py install```

results in the following error
```
Required dependencies:
    Python Imaging Library .......
    ... Not found
```

After I installed Pillow globally 
```sudo pip3 install Pillow```

Then I could run the install script successfully, and now it's working.  Installing packages globally doesn't appear to be a common Python practice from what I could find, but maybe it's needed in certain situations like here.  Posting this in case it helps others.

Thanks for developing this - thumbnails make a big difference!

**Comment by marianosimone** [comment]
Thanks for reporting!

This is the first time I hear about problems with this. Would you mind giving more information about your distribution and version?

The installation instructions are vague on purpose, as it's hard to give exact instructions for all combinations of distributions, versions, and personal preferences:

> install it with pip install Pillow or with package manager from your distro

**Comment by greendost** [comment]
Sure, I am running Linux PopOs 22.04, which I think is based on Ubuntu.  I was not able to install it with apt-get, which probably would have worked too; perhaps it's no longer in the default repositories.

**Comment by marianosimone** [comment]
Thanks! I just added a note about this in the README
