### ISSUE TITLE
License

### ISSUE THREAD

**Issue by GaetanLepage** [marianosimone/epub-thumbnailer#45]
Hi,
Could you please consider adding a license to this software ?

Thanks for the project !

**Comment by GaetanLepage** [comment]
I asked this because I packaged your software to Nixpkgs: https://github.com/NixOS/nixpkgs/pull/298771
There, we report the license. When it is missing, the package is marked as "unfree" and thus can only be installed by users explicitly allowing unfree software.
Since the moment of opening this issue, we encountered the GPL3 banner in [epub-thumbnailer.py](https://github.com/marianosimone/epub-thumbnailer/blob/master/src/epub-thumbnailer.py). Hence, we marked the package as GPL3.

**Comment by marianosimone** [comment]
Oh, forgot about that 🤦🏽 
Just added a LICENSE file

**Comment by GaetanLepage** [comment]
Thanks !
