### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by bobbitybob** [marianosimone/epub-thumbnailer#7]
Getting this message when trying to install (Arch Linux). Seems to be a python version issue. Does this work on python 3? Thanks.

**Comment by marianosimone** [comment]
Thanks for the report @bobbitybob. I've never tried it on Python 3, so I'm not sure the whole thing works... but now I changed the print statement to at least let you install it. Please let me know if you find any other issues trying to use Python 3
